# Generated by Django X.Y on YYYY-MM-DD HH:MM
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentRh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.CharField(max_length=100)),
                ('fichier', models.FileField(upload_to='rh/documents/')),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents_rh', to='institutions.employe')),
            ],
        ),
        migrations.CreateModel(
            name='ContratTravail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_contrat', models.CharField(max_length=50)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('fichier_contrat', models.FileField(blank=True, null=True, upload_to='rh/contrats/')),
                ('statut', models.CharField(blank=True, max_length=50, null=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrats', to='institutions.employe')),
            ],
        ),
        migrations.CreateModel(
            name='HistoriquePoste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poste', models.CharField(max_length=100)),
                ('agence', models.CharField(blank=True, max_length=100, null=True)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('type_mouvement', models.CharField(blank=True, max_length=50, null=True)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiques_poste', to='institutions.employe')),
            ],
        ),
        migrations.CreateModel(
            name='DonneeRhEmploye',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut_rh', models.CharField(blank=True, max_length=50, null=True)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donnees_rh', to='institutions.employe')),
            ],
        ),
    ]
