# Generated by Django 4.2.23 on 2025-06-17 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0001_initial'),
        ('rh', '0003_horairestandard_jourferie_horaireemploye_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeAbsence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DemandeConge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('valide', 'Validée'), ('refuse', 'Refusée')], default='en_attente', max_length=30)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_conge', to='institutions.employe')),
                ('type_absence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rh.typeabsence')),
            ],
        ),
        migrations.CreateModel(
            name='AbsenceEmploye',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('motif', models.CharField(blank=True, max_length=255, null=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('valide', 'Validée'), ('refuse', 'Refusée')], default='en_attente', max_length=30)),
                ('justificatif', models.FileField(blank=True, null=True, upload_to='rh/absences/')),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='institutions.employe')),
                ('type_absence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rh.typeabsence')),
            ],
        ),
    ]
