# Generated by Django 4.2.23 on 2025-06-17 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0001_initial'),
        ('rh', '0004_typeabsence_demandeconge_absenceemploye'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pointage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('heure', models.TimeField()),
                ('type', models.CharField(choices=[('entree', 'Entrée'), ('sortie', 'Sortie'), ('pause', 'Pause')], max_length=10)),
                ('source', models.CharField(choices=[('manuel', 'Manuel'), ('automatique', 'Automatique')], default='manuel', max_length=20)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pointages', to='institutions.employe')),
            ],
        ),
    ]
