# Generated by Django 4.2.23 on 2025-06-22 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agences', '0002_initial'),
        ('rh', '0007_formation_sessionformation_evaluation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointage',
            name='agence',
            field=models.ForeignKey(blank=True, help_text='Agence liée au pointage', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pointages', to='agences.agence', verbose_name='Agence de pointage'),
        ),
        migrations.AlterField(
            model_name='pointage',
            name='source',
            field=models.CharField(choices=[('qr_code', 'QR Code'), ('geolocalisation', 'Geolocalisation')], default='manuel', max_length=20),
        ),
        migrations.AlterField(
            model_name='pointage',
            name='type',
            field=models.CharField(choices=[('arrivee', 'Arrivée'), ('depart', 'Départ')], max_length=10),
        ),
    ]
