# Generated by Django 5.2.3 on 2025-06-30 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0008_pointage_agence_alter_pointage_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointage',
            name='source',
            field=models.CharField(choices=[('qr_code', 'QR Code'), ('geolocalisation', 'Geolocalisation'), ('manuel', 'Manuel')], default='manuel', max_length=20),
        ),
    ]
