# Generated by Django 4.2.23 on 2025-07-21 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0003_alter_employe_telephone'),
        ('rh', '0009_alter_pointage_source'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pointage',
            unique_together={('employe', 'date', 'type')},
        ),
    ]
