# Generated by Django 4.2.23 on 2025-07-21 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0010_alter_pointage_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pointage',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='pointage',
            constraint=models.UniqueConstraint(fields=('employe', 'date', 'type'), name='unique_pointage_employe_date_type'),
        ),
    ]
