# Generated by Django 4.2.23 on 2025-06-16 16:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('roles_permissions', '0001_initial'),
        ('agences', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut_utilisateur', models.CharField(choices=[('employe', 'Employé'), ('client', 'Client'), ('partenaire', 'Partenaire'), ('autre', 'Autre')], default='autre', max_length=20)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin'), ('Autre', 'Autre')], max_length=10)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('numero_cni', models.CharField(blank=True, max_length=50, null=True)),
                ('nationalite', models.CharField(blank=True, max_length=50, null=True)),
                ('lieu_naissance', models.CharField(blank=True, max_length=100, null=True)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('date_embauche', models.DateField(blank=True, null=True)),
                ('date_fin_contrat', models.DateField(blank=True, null=True)),
                ('type_contrat', models.CharField(blank=True, choices=[('CDI', 'CDI'), ('CDD', 'CDD'), ('Stage', 'Stage'), ('Autre', 'Autre')], max_length=20, null=True)),
                ('periode_essai', models.CharField(blank=True, max_length=100, null=True)),
                ('statut_rh', models.CharField(blank=True, choices=[('actif', 'Actif'), ('inactif', 'Inactif'), ('demissionne', 'Démissionné'), ('licencie', 'Licencié')], max_length=20, null=True)),
                ('horaire_travail', models.CharField(blank=True, max_length=100, null=True)),
                ('matricule_interne', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('salaire_base', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('primes', models.JSONField(blank=True, default=dict, null=True)),
                ('retenues', models.JSONField(blank=True, default=dict, null=True)),
                ('rib_banque', models.CharField(blank=True, max_length=50, null=True)),
                ('heures_supplementaires', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('variables_paie', models.JSONField(blank=True, default=dict, null=True)),
                ('diplomes', models.JSONField(blank=True, default=list, null=True)),
                ('langues', models.JSONField(blank=True, default=list, null=True)),
                ('competences', models.JSONField(blank=True, default=list, null=True)),
                ('evaluations', models.JSONField(blank=True, default=list, null=True)),
                ('objectifs', models.JSONField(blank=True, default=list, null=True)),
                ('mobilite', models.CharField(blank=True, max_length=100, null=True)),
                ('besoins_formation', models.JSONField(blank=True, default=list, null=True)),
                ('plan_formation', models.JSONField(blank=True, default=list, null=True)),
                ('sessions_suivies', models.JSONField(blank=True, default=list, null=True)),
                ('certifications', models.JSONField(blank=True, default=list, null=True)),
                ('absences_calculees', models.IntegerField(blank=True, null=True)),
                ('maladies', models.JSONField(blank=True, default=list, null=True)),
                ('accidents', models.JSONField(blank=True, default=list, null=True)),
                ('visites_medicales', models.JSONField(blank=True, default=list, null=True)),
                ('restrictions_medicales', models.JSONField(blank=True, default=list, null=True)),
                ('risques_professionnels', models.JSONField(blank=True, default=list, null=True)),
                ('representation_personnel', models.BooleanField(default=False)),
                ('reunions', models.JSONField(blank=True, default=list, null=True)),
                ('sanctions', models.JSONField(blank=True, default=list, null=True)),
                ('reclamations', models.JSONField(blank=True, default=list, null=True)),
                ('contentieux', models.JSONField(blank=True, default=list, null=True)),
                ('date_depart', models.DateField(blank=True, null=True)),
                ('motif_depart', models.CharField(blank=True, max_length=150, null=True)),
                ('solde_tout_compte', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('attestation_travail', models.FileField(blank=True, null=True, upload_to='attestations/')),
                ('entretien_sortie', models.TextField(blank=True, null=True)),
                ('droits_post_emploi', models.JSONField(blank=True, default=list, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('agence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agences.agence')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='roles_permissions.role')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
