# Generated by Django 4.2.23 on 2025-06-16 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutions', '0001_initial'),
        ('agences', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agence',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agences', to='institutions.institution'),
        ),
    ]
