# Generated by Django 4.2.23 on 2025-07-28 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0003_alter_employe_telephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='matricule_interne',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
    ]
