name: Snyk Security Scan - Expo React Native

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  security-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Setup Snyk CLI
        uses: snyk/actions/setup@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Run Snyk Open Source Scan (SCA)
        run: |
          snyk test --all-projects --json-file-output=snyk-scanner-results.json || true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Run Snyk Code Scan (SAST)
        run: |
          snyk code test --sarif-file-output=snyk-code.sarif --json-file-output=snyk-code-results.json || true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Generate HTML Reports
        run: |
          npx snyk-to-html -i snyk-scanner-results.json -o snyk-scanner-report.html
          npx snyk-to-html -i snyk-code-results.json -o snyk-code-report.html

      - name: Upload Reports
        uses: actions/upload-artifact@v4
        with:
          name: snyk-security-reports
          path: |
            snyk-scanner-report.html
            snyk-code-report.html
            snyk-scanner-results.json
            snyk-code-results.json
            snyk-code.sarif

      - name: Reminder: vous pouvez voir votre rapport
        run: echo "::notice ::✅ Download the Snyk reports from the 'Artifacts' section at the bottom of this page."

      - name: Monitor in Snyk Dashboard
        run: snyk monitor --all-projects
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
