name: Snyk Security Scan - React Native

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule:
    - cron: '0 0 * * *' # Exécution quotidienne

permissions:
  contents: read
  security-events: write

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm install
          cd ios && pod install && cd .. # Pour les dépendances iOS si nécessaire

      - name: Setup Snyk CLI
        uses: snyk/actions/setup@806182742461562b67788a64410098c9d9b96adb
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      # Scan Snyk Open Source (SCA)
      - name: Run Snyk Open Source test (SCA)
        run: |
          snyk test --all-projects --json-file-output=snyk-scanner-results.json --detection-depth=6
          echo "SCA results saved to snyk-scanner-results.json"
        
      # Scan Snyk Code (SAST)
      - name: Run Snyk Code test (SAST)
        run: |
          snyk code test --sarif > snyk-code.sarif --json-file-output=snyk-code-results.json
          echo "SAST results saved to snyk-code.sarif and snyk-code-results.json"

      # Scan Snyk IaC (Infrastructure as Code)
      - name: Run Snyk IaC test
        run: |
          snyk iac test --sarif > snyk-iac.sarif --json-file-output=snyk-iac-results.json
          echo "IaC results saved to snyk-iac.sarif and snyk-iac-results.json"

      # Envoi des résultats à GitHub Code Scanning
      - name: Upload SAST results to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk-code.sarif

      # Génération des rapports HTML
      - name: Generate HTML reports
        run: |
          npm install -g snyk-to-html
          snyk-to-html -i snyk-scanner-results.json -o snyk-scanner-report.html
          snyk-to-html -i snyk-code-results.json -o snyk-code-report.html
          snyk-to-html -i snyk-iac-results.json -o snyk-iac-report.html
          echo "HTML reports generated"

      # Archivage des rapports pour téléchargement
      - name: Archive vulnerability reports
        uses: actions/upload-artifact@v3
        with:
          name: snyk-security-reports
          path: |
            snyk-scanner-report.html
            snyk-code-report.html
            snyk-iac-report.html
            snyk-scanner-results.json
            snyk-code-results.json
            snyk-iac-results.json

      # Envoi des résultats à Snyk pour suivi
      - name: Monitor dependencies in Snyk
        run: snyk monitor --all-projects
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
