name: Snyk Security Scan - Expo React Native

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"  # Expo recommande Node 18+ (v19+ pour React 19)
          cache: "npm"

      - name: Install dependencies
        run: npm install --legacy-peer-deps  # Ignore les conflits de peerDependencies

      - name: Setup Snyk CLI
        uses: snyk/actions/setup@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Run Snyk Open Source Scan (SCA)
        run: |
          snyk test --all-projects --json-file-output=snyk-scanner-results.json
          echo "SCA scan completed"

      - name: Run Snyk Code Scan (SAST)
        run: |
          snyk code test --sarif > snyk-code.sarif --json-file-output=snyk-code-results.json
          echo "SAST scan completed"

      - name: Generate HTML Reports
        run: |
          npx snyk-to-html -i snyk-scanner-results.json -o snyk-scanner-report.html
          npx snyk-to-html -i snyk-code-results.json -o snyk-code-report.html

      - name: Upload Reports
        uses: actions/upload-artifact@v4
        with:
          name: snyk-security-reports
          path: |
            snyk-scanner-report.html
            snyk-code-report.html
            snyk-scanner-results.json
            snyk-code-results.json

      - name: Monitor in Snyk Dashboard
        run: snyk monitor --all-projects
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
