name: Snyk Security Scan - Expo React Native + Django

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  security-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Check for package.json and lock file
        run: |
          if [ -f package.json ]; then
            echo "package.json found."
            if [ -f package-lock.json ]; then
              echo "package-lock.json found. Running npm ci..."
              npm ci
            else
              echo "No package-lock.json found. Running npm install..."
              npm install --legacy-peer-deps
            fi
          else
            echo "No package.json found. Skipping Node.js dependencies install."
          fi

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Setup Snyk CLI
        uses: snyk/actions/setup@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Run Snyk Open Source Scan (SCA)
        run: snyk test --all-projects --json-file-output=snyk-scanner-results.json || true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Run Snyk Code Scan (SAST)
        run: snyk code test --sarif-file-output=snyk-code.sarif --json-file-output=snyk-code-results.json || true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Generate HTML Reports
        run: |
          npx snyk-to-html -i snyk-scanner-results.json -o snyk-scanner-report.html
          npx snyk-to-html -i snyk-code-results.json -o snyk-code-report.html
          npx html-pdf-cli snyk-scanner-report.html snyk-scanner-report.pdf || true
          npx html-pdf-cli snyk-code-report.html snyk-code-report.pdf || true

      - name: Upload Reports
        uses: actions/upload-artifact@v4
        with:
          name: snyk-security-reports
          path: |
            snyk-scanner-report.html
            snyk-code-report.html
            snyk-scanner-report.pdf
            snyk-code-report.pdf
            snyk-scanner-results.json
            snyk-code-results.json
            snyk-code.sarif

      - name: Share Download Link
        run: echo "Télécharge le rapport PDF depuis l'onglet Actions > run > Artifacts."

      - name: Monitor in Snyk Dashboard
        run: snyk monitor --all-projects || true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
